### ISSUE TITLE
Data too long for column 'session_id'

### ISSUE THREAD

**Issue by exodus4d** [bcosca/fatfree#950]
I got a Bug report for my project: https://github.com/exodus4d/pathfinder/issues/273

```
2016/07/30 00:24:24 [error] 26299#26299: *646 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session_id' at row 1 in /srv/www/htdocs/app/lib/db/sql.php:202
Stack trace:
#0 /srv/www/htdocs/app/lib/db/sql.php(202): PDOStatement->execute()
#1 /srv/www/htdocs/app/lib/db/sql/mapper.php(418): DB\SQL->exec(Array, Array)
#2 /srv/www/htdocs/app/lib/db/cursor.php(242): DB\SQL\Mapper->insert()
#3 /srv/www/htdocs/app/lib/db/sql/session.php(94): DB\Cursor->save()
#4 [internal function]: DB\SQL\Session->write('49n55saan9n48b6...', '')
#5 /srv/www/htdocs/app/lib/base.php(1910): session_commit()
#6 [internal function]: Base->unload('/srv/www/htdocs')
#7 {main}
thrown in /srv/www/htdocs/app/lib/db/sql.php on line 202" while reading upstream, client: 17.87.40.7, server: pathfinder.unknown.cz, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "pathfinder.unknown.cz", referrer: "https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fpathfinder.uknown.cz%2Fsso%2FcallbackAuthorization&client_id=6c1a30d6cd79463281491f7153a9b5dd&scope=characterLocationRead%20characterNavigationWrite&state=e38c78c4d16d4298588abffc"
```

It looks like `VARCHAR(40)` can not handle some long IDs. 
**DB Version:** MySQL 5.6 
**Code:** https://github.com/bcosca/fatfree/blob/master/lib/db/sql/session.php#L181

**Comment by Rayne** [comment]
It looks like our magic number should be `45` instead of `40` because of IPv4 tunneling.

Source: [Maximum length of the textual representation of an IPv6 address?](http://stackoverflow.com/a/166157/870798)

**Comment by sn0opy** [comment]
https://github.com/bcosca/fatfree-core/pull/148 has been merged
